channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - networkx=2.4
  - matplotlib=3.2.2
  - pandas=1.0.5
  - nltk=3.5
  - pillow=7.2.0
  - pysimplegui=4.56.0
  - lxml=4.5.2
  - openpyxl=3.0.9
