channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2023.05.30
  - certifi=2022.12.7
  - click=8.0.4
  - cycler=0.11.0
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - flit-core=3.6.0
  - freetype=2.12.1
  - icu=58.2
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgomp=13.1.0
  - libnsl=2.0.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.5.2
  - lz4-c=1.9.4
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - networkx=2.4
  - nltk=3.5
  - numpy=1.21.5
  - numpy-base=1.21.5
  - olefile=0.46
  - openpyxl=3.0.9
  - openssl=3.0.10
  - pandas=1.0.5
  - pillow=7.2.0
  - pip=22.3.1
  - pyparsing=3.0.9
  - pysimplegui=4.56.0
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2022.7
  - readline=8.2
  - regex=2022.7.9
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.1
  - typing_extensions=4.4.0
  - wheel=0.38.4
  - xz=5.2.10
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5